[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.20"

[features]
resolution = true
skip-lint = false

[programs.localnet]
burry_escrow = "DDFpiq1hQUmXPr6RvnYw4srpRjeDzGjkVNBZdr4oNfSw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test --timeout 120000"
